name: .NET

on:
  push:
    branches: [ main ]
    paths: "Backend/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore WebApi.sln
    - name: Build
      run: dotnet build WebApi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test WebApi.sln --verbosity normal
