name: .NET

on:
  push:
    branches: [ main ]
    paths: "Backend/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/Backend.csproj
    - name: Build
      run: dotnet build Backend/Backend.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/tests.csproj --no-build --verbosity normal
